# Use an official Nginx image as the base image
FROM nginx:alpine

# Copy the HTML file from the current directory into the container at /usr/share/nginx/html
COPY index.html /usr/share/nginx/html

# Expose port 80 to allow external access to the web server running inside the container
EXPOSE 80
